#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sat Oct 25 18:18:31 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from mcom import *	#mcomのクラス定義ファイルをインポート
mcom = Mcom()	#Mcomのインスタンス生成

time.sleep(2)		#Arduinoの起動待ち



class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _(u"起動まで"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _(u"秒"))
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _(u"破壊まで"))
        self.label_5 = wx.StaticText(self, wx.ID_ANY, "")
        self.label_6 = wx.StaticText(self, wx.ID_ANY, _(u"秒"))
        self.button_1 = wx.Button(self, wx.ID_ANY, _(u"リセット"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _(u"終了"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.Bind(wx.EVT_BUTTON, self.reset_button, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.exit_button, self.button_2)

        self.timer = wx.Timer(self)
        self.Bind(wx.EVT_TIMER, self.refresh)
        self.timer.Start(500)

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle(_("MCOM Monitor"))
        self.label_1.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_2.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_3.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_4.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_5.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.label_6.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_1.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        self.button_2.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Sans"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL,  0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ALIGN_CENTER_HORIZONTAL,  0)
        grid_sizer_1.Add(self.label_6, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()

    def reset_button(self, event):  # wxGlade: MainWindow.<event_handler>
        mcom.reset()

    def exit_button(self, event):  # wxGlade: MainWindow.<event_handler>
        exit()


    def refresh(self, event):

        mcom.getdata()
        if mcom.mcom_mode == 0:
            self.mode0()

        elif mcom.mcom_mode == 1:
            self.mode1()

        elif mcom.mcom_mode == 2:
            self.mode2()

	elif mcom.mcom_mode == 3:
            self.mode3()


    def mode0(self):
        self.label_1.SetLabel(u"起動まで")
        self.label_2.SetLabel(mcom.disengage)
        self.label_3.SetLabel(u"秒長押し")

        self.label_4.SetLabel(u"")
        self.label_5.SetLabel(u"")
        self.label_6.SetLabel(u"")


    def mode1(self):
        self.label_1.SetLabel(u"解除まで")
        self.label_2.SetLabel(mcom.disengage)
        self.label_3.SetLabel(u"秒長押し")

        self.label_4.SetLabel(u"破壊まで")
        self.label_5.SetLabel(mcom.left)
        self.label_6.SetLabel(u"秒")

    def mode2(self):
        self.label_1.SetLabel(u"解除まで")
        self.label_2.SetLabel(mcom.disengage)
        self.label_3.SetLabel(u"秒長押し")

        self.label_4.SetLabel(u"破壊まで")
        self.label_5.SetLabel(mcom.left)
        self.label_6.SetLabel(u"秒")

    def mode3(self):
        self.label_1.SetLabel("破壊済み")
        self.label_2.SetLabel("")
        self.label_3.SetLabel("")

        self.label_4.SetLabel("")
        self.label_5.SetLabel("")
        self.label_6.SetLabel("")


        # end wxGlade

# end of class MainWindow
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainWindow(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
